-- Migration: Add ICT-specific columns to trades table
-- New columns for ICT-based discretionary trading journal

ALTER TABLE trades ADD COLUMN IF NOT EXISTS session TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS kill_zone TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS htf_timeframe TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS htf_bias TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS trend_alignment TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS entry_model TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS htf_poi BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS liquidity_sweep BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS mss_confirmed BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS fvg_present BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS ifvg_present BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS breaker_block_retest BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS order_block_retest BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS fibonacci_retracement BOOLEAN DEFAULT false;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS emotion_before INTEGER;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS emotion_after INTEGER;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS emotion_tags TEXT[];
ALTER TABLE trades ADD COLUMN IF NOT EXISTS mistake_tags TEXT[];
ALTER TABLE trades ADD COLUMN IF NOT EXISTS entry_reason TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS exit_reason TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS trade_cause TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS invalidation TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS retake_trade TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS lesson_learned TEXT;
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rr_planned DECIMAL(10, 2);
ALTER TABLE trades ADD COLUMN IF NOT EXISTS rr_achieved DECIMAL(10, 2);
